name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Install Dependencies
        run: npm install

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Build Application
        run: npm run build

      - name: Start Application
        run: |
          sshpass -p '${{ secrets.DROPLET_PASSWORD }}' ssh root@165.227.41.29 "cd /tsphere-backend && npm start"